### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by zackproser**

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Shouldn't you be on the list too Zack?

**Comment by zackproser** [comment]
> Shouldn't you be on the list too Zack?

Busted :laughing:

**Comment by zackproser** [comment]
> > Shouldn't you be on the list too Zack?
> 
> Busted laughing

Fixed!

**Review by brikis98 — APPROVED** [review]
LGTM

**Comment by zackproser** [comment]
Thanks for reviewing!

**Pull request merged**
