### PR TITLE
Rate limit github clone calls

### LINKED ISSUE #139: Rate limiting for repository cloning?
**Describe the solution you'd like**
The ability to rate limit repository cloning operations

**Describe alternatives you've considered**
None

**Additional context**
I'm attempting to do a bulk operation on an org containing 176 repositories, but github is resetting the connection on all these clone operation attempts. It appears that the cloning is all being done in parallel, and my guess is that it's rate limiting operations. I see there's rate limiting on creating pull requests; perhaps applying a similar solution for the cloning operations would allow things to complete. Currently the operations are just failing without retries.

### PR DESCRIPTION
**Pull request by cbrand**
## Description

Fixes #139.

Add rate limiting to github clone calls, avoiding issues with github "permission denied" and EOF errors when cloning too many repositories in parallel.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes

Added
- Rate limiting Github Clone calls to 4 per default, allows being parametrized by the `--max-concurrent-clones` flag

### Migration Guide

None needed

### CODE REVIEW

**Comment by XavierChanth** [comment]
For the reviewers, I was able to build git-xargs and used this build to clone ~80 repos mostly successfully, where the current release was only cloning 1 repo.

**Comment by flinn** [comment]
@brikis98 @hongil0316 What all is necessary in order to help get these changes merged/published? Asking as we've started to use git-xargs recently and without this feature we'll be very unlikely to proceed in using this tool as we're attempting to use it across ~300+ repositories.

**Comment by yogur** [comment]
We have 2000+ repos to update and I had to use a script to execute `git-xargs` in batches of 50 repos to go around repo clone rate-limiting, which somewhat defeats the purpose of batching offered by this tool! 

I compiled the changes in this PR and used it. It solved our issue! Would be great if it gets merged soon.

**Comment by james03160927** [comment]
Sorry for the delay. It seems like some of the tests for repository is failing. Can you make sure those tests pass? 
> FAIL    github.com/gruntwork-io/git-xargs/repository    300.028s

**Comment by james03160927** [comment]
Friendly ping on this PR.

**Comment by cbrand** [comment]
@james03160927 Hey I had a chance to take a look and seem to have fixed the unit tests. Please take another look:
```
?   	github.com/gruntwork-io/git-xargs/common	[no test files]
?   	github.com/gruntwork-io/git-xargs/config	[no test files]
?   	github.com/gruntwork-io/git-xargs/local	[no test files]
?   	github.com/gruntwork-io/git-xargs/mocks	[no test files]
?   	github.com/gruntwork-io/git-xargs/printer	[no test files]
?   	github.com/gruntwork-io/git-xargs/stats	[no test files]
?   	github.com/gruntwork-io/git-xargs/util	[no test files]
ok  	github.com/gruntwork-io/git-xargs	0.488s
ok  	github.com/gruntwork-io/git-xargs/auth	0.223s
ok  	github.com/gruntwork-io/git-xargs/cmd	1.893s
ok  	github.com/gruntwork-io/git-xargs/io	0.680s
ok  	github.com/gruntwork-io/git-xargs/repository	2.154s
ok  	github.com/gruntwork-io/git-xargs/types	1.158s
```

**Review by james03160927 — APPROVED** [review]
LGTM. Passed all the tests.

**Pull request merged**
