### PR TITLE
Add GitHub PR & Issue Templates

### PR DESCRIPTION
**Pull request by robmorgan**
This PR adds GitHub PR & Issue templates as part of our new coding methodology.

### CODE REVIEW

**Review by zackproser — DISMISSED** [review]
LGTM :+1:

**Comment by robmorgan** [comment]
@zackproser I did some minor changes including the URL, so I'll need a re-approval 👍

**Review by zackproser — APPROVED** [review]
LGTM :+1:

**Review by zackproser — APPROVED** [review]
LGTM

**Pull request merged**
